defaults:
  - dataset: synth_pc

plot:
  max_points_per_class: 05000
  projection: dims        # pca | dims
  dim0: 0
  dim1: 1
  kde_levels: 20
  kde_thresh: 0.0
  cmap: rocket_r
  out_name: synth_pointclouds_kde.png
  dpi: 200
